### ISSUE TITLE
read complexity dataframe from csv

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/dataframe#62]
We can write a hierarchical dataframe to CSV, but when we read it, we get a flat dataframe where the columns are of string type:

```kotlin
val df = mapOf("name" to listOf("a","b","b","c","a","a","b","b","c","a"),
              "number" to listOf(1,2,3,1,3,2,3,2,1,3)).toDataFrame()

val df1 = df.groupBy("name").pivot("number", inward = false).aggregate { 
                count() into "count"
                mean() into "mean"
            }
```

If look at the df1 diagram, it will look like this:

```
name: String
1:
    count: Int?
    mean:
        number: Double?
3:
    count: Int?
    mean:
        number: Double?
2:
    count: Int?
    mean:
        number: Double?
```

Let's write df1 to csv and read from it:
```kotlin
df1.writeCSV("sample.csv")

DataFrame.read("sample.csv").schema().print()
```

On the dataframe read from CSV, the scheme is already like this:
```
name: String
1: String
3: String
2: String
```
